# Generated by Django 5.2.1 on 2025-12-22 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DBInventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InventoryTypes_Tables',
            new_name='InventoryTypesTables',
        ),
    ]
